### ISSUE TITLE
The speed and receptive field of the model

### ISSUE THREAD

**Issue by Liujingxiu23** [chomeyama/HN-UnifiedSourceFilterGAN#3]
Thank you for your work and sharing. 
Since I have to use the vocoder model on online sevice, I want to know:
Does the model has a certain receptive field so that I can do inference in stream mode?
And what about the speed when infer in CPU, compared with melgan or hifigan?
Thank you again.

**Comment by chomeyama** [comment]
Thank you for your interest in my work!

> Does the model has a certain receptive field so that I can do inference in stream mode?
Sorry, I have never tried to use the vocoder for real-time uses. However, since it consists of PWG with some convolution layers as an extra, some application examples of PWG might be informative.

> And what about the speed when infer in CPU, compared with melgan or hifigan?
Hn-uSFGAN has a larger RTF than the up-sampling-based neural vocoders.
The RTF of hn-uSFGAN is about 1.2 on a single CPU, Intel Xeon Gold 6142 (and 0.036 on a single GPU, Titan RTX 3090).

**Comment by Liujingxiu23** [comment]
Thank you very much for your reply!
I used hifigan as vocoder in singing voice synthesis, but glitches occurs in the synthsized waves especially in long vowel part.
May be I should merge the concept of "Source-Filter" to have a try.
